name: secret🤫
run-name: secret🤫
on: 
  push:
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $MY_VAR
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
        hello
